// src/lib/components/Right.svelte
<script lang="ts">
  import Background from '$comps/Background.svelte'
  import Arrow from '$comps/Arrow.svelte'
  import SourceButton from '$comps/SourceButton.svelte'
  import { sourceButtonData } from '$lib'
  import type { Holiday } from '$lib/types'
  export let holiday: Holiday = ''
</script>

<div class={`right ${holiday ?? ""}`}>
  {#if holiday}
    <Background holiday={holiday} />
  {/if}
  <slot name="outside-card-flow" />
  <div class="right-liner">
    {#if holiday}
      <SourceButton data={sourceButtonData[holiday]} /> 
      <Arrow />
    {/if}
    <div class="card-wrapper" >
      <slot />
    </div>
  </div>
</div>

<style>
.right {
  background: rgb(var(--bg-color-2));
  position: relative;
  flex: 3;
  padding: 0;
  overflow: visible;
  align-self: stretch;
  display: flex;
  flex-direction: column;
  /* height: auto; */
}
.card-wrapper {
  display: flex;
  flex-wrap: wrap;
  justify-content: center;
  position: relative;
  gap: 20px;
  padding: 0 20px 77vh 20px;
}
.right:not(.halloween, .winter) .card-wrapper {
  padding-block: 7vh;
}
</style>

// src/components/Right/right.tsx
import { Slot, component$ } from "@builder.io/qwik";
import { css } from "~/styled-system/css";
import { Background } from "../Background/background";
import { Arrow } from "~/components/Arrow/arrow";

export interface RightProps {
  holiday: string;
}

export const Right = component$<RightProps>((props) => {
  return (
    <div
      class={
        props.holiday +
        " " +
        css({
          background: "rgb(var(--fg-color-2))",
          position: "relative",
          flex: 3,
          width: "100%",
          overflow: "auto",
          height: "100%",
          display: "grid",
          "& .card-wrapper": {
            display: "flex",
            flexDirection: "column",
            // gridArea: "1 / 1 / 2 / 2",
            paddingBlock: "77vh",
            gap: "20px",
          },
        })
      }
    >
      <Background holiday={props.holiday} />

      <div class="card-wrapper">
        {/* ghost has to be inside card-wrapper for the z-index layering to work */}
        <div
          class={css({
            width: "100%",
            display: "flex",
            justifyContent: "center",
            position: "relative",
            // pointerEvents: "none",
          })}
        >
          <Arrow />
        </div>
        <Slot />
      </div>
    </div>
  );
});
