// src/components/Background/background.tsx
import { component$ } from "@builder.io/qwik";
import { css } from "~/styled-system/css";
import ScaryNewberry from "~/media/scarynewberry-cropped-overlay.jpg?jsx";
import SpookyNewberry from "~/media/spookynewberry.png?jsx";
// import ChillyNewberry from "~/media/scarynewberry-cropped.png?jsx";

import Snowflake1 from "~/media/snow/winter-bg-snowflakes-1.png?jsx";
import Snowflake2 from "~/media/snow/winter-bg-snowflakes-2.png?jsx";
import Snowflake3 from "~/media/snow/winter-bg-snowflakes-3.png?jsx";
import Snowflake4 from "~/media/snow/winter-bg-snowflakes-4.png?jsx";
import Snowflake5 from "~/media/snow/winter-bg-snowflakes-5.png?jsx";
import Snowflake6 from "~/media/snow/winter-bg-snowflakes-6.png?jsx";

const snowflakes = [
  <Snowflake1 key="flake1" />,
  <Snowflake2 key="flake2" />,
  <Snowflake3 key="flake3" />,
  <Snowflake4 key="flake4" />,
  <Snowflake5 key="flake5" />,
  <Snowflake6 key="flake6" />,
];
import Wintry from "~/media/wintry.png?jsx";
// import { Snowflake } from "../Snowflake/snowflake";

export interface BackgroundProps {
  holiday: string;
}
export const Background = component$<BackgroundProps>((props) => {
  return (
    <div
      class={
        props.holiday +
        " " +
        css({
          // position: "fixed",
          overflow: "hidden",
          pointerEvents: "none",
          zIndex: 0,
          gridArea: "1 / 1 / 2 / 2",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          alignItems: "stretch",
          // backgroundImage: `linear-gradient(to bottom, rgba(0,0,0,0.87), rgba(0,0,0,0.37))`,
          "& .tint": {
            width: "100%",
            flex: 1,
            background:
              "linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0) 60vh, rgba(var(--bg-color-2),1) 85%, rgba(var(--bg-color-2),1) 100%)",
          },
          "& .spooky": {
            display: "flex",
            flexDirection: "column",
            justifyContent: "flex-end",
            alignItems: "flex-start",
            background: "rgba(241,97,81,1)",
            "& img": {
              width: "100%",
            },
          },
          "& .scary": {
            position: "fixed",
            top: 0,
            width: "100%",
            lg: {
              width: "80%",
            },
            "& img": {
              position: "relative",
              width: "100%",
              // objectPosition: "80% 50%",
              objectFit: "cover",
              height: "100vh",
            },
          },
          "& img": {
            overflow: "hidden",
            objectFit: "cover",
            margin: 0,
            objectPosition: "center",
          },
          "& .sno-1, .sno-2, .sno-3": {
            display: "none",
          },
          md: {
            "& .sno-1": {
              display: "block",
            },
            "& .sno-2, .sno-3": {
              display: "none",
            },
          },
          lg: {
            "& .sno-1, .sno-2": {
              display: "block",
            },
            "& .sno-3": {
              display: "none",
            },
          },
          xl: {
            "& .sno-1, .sno-2, .sno-3": {
              display: "block",
            },
          },
        }) +
        " background"
      }
    >
      <div class="scary">
        {props.holiday === "halloween" ? (
          <ScaryNewberry />
        ) : props.holiday === "winter" ? (
          <Wintry />
        ) : (
          ""
        )}
      </div>
      <div class="tint">
        <span></span>
        {props.holiday === "winter" ? (
          Array.from({ length: 200 }).map((_, i) => (
            <div key={i} class={`snow sno-${Math.floor(i / 50)}`}>
              {snowflakes[(i % 6) + 1]}
            </div>
          ))
        ) : (
          <span></span>
        )}
      </div>
      <div class="spooky">
        {props.holiday === "halloween" ? (
          <SpookyNewberry />
        ) : props.holiday === "winter" ? (
          <span></span>
        ) : (
          ""
        )}
      </div>
    </div>
  );
});

// src/lib/components/Background.svelte
<script>
export let holiday

// halloween and winter images are declared here; 
// in the html section below, if holiday isn't one of those 2, there's no <img> at all
const topImage = holiday === 'halloween' ? '/scary-newberry.webp' : '/wintry-newberry.webp'  
</script>

<div class={holiday + ' background'}>
  <div class="background-top">
    {#if holiday}
      <img src={topImage} alt="" /> 
    {/if}
  </div>
  <div class="background-middle">
    {#if 'winter' === holiday}
      {#each Array.from({length: 199}) as _, i}
        <div class={`snow sno-${Math.floor(i / 50)}`}>
          <img src={`/snow/snowflake-${i % 6 + 1}.webp`} alt="">
        </div>
      {/each}
    {:else}
      <span></span>
    {/if}
  </div>
  <div class="background-bottom">
    {#if 'halloween' === holiday}
      <img src="/spooky-newberry.webp" alt="" />
    {:else}
      <span></span>
    {/if}
  </div>
</div>

<style>
.background {
  grid-area: 1 / 1 / 2 / 2;
  position: absolute;
  overflow: hidden;
  pointer-events: none;
  height: 100%;
  width: 100%;
  display: flex;
  flex-direction: column;
  justify-content: space-between;
  align-items: stretch;
}
.background-top {
  position: fixed;
  top: 0;
  /* width: 100%; <--- media query, below */
}
.background-top img {
  position: relative;
  width: 100%;
  height: 100vh;
}
.background-middle {
  height: 100%;
  width: 100%;
  flex: 1 1 0%;
  background: linear-gradient(to bottom, rgba(0,0,0,0) 0%, rgba(0,0,0,0) 60vh, rgba(var(--bg-color-2),1) 85%, rgba(var(--bg-color-2),1) 100%);
}
.background-bottom {
  display: flex;
  flex-direction: column;
  justify-content: end;
  align-items: start;
  background: rgba(var(--bg-color-2), 1);
}
.background-bottom img {
  width: 100%;
  /* height: 100vh; */
}
img {
  overflow: hidden;
  object-fit: cover;
  object-position: center;
  margin: 0;
}
@media screen and (max-width: 1023px){
  .background-top {
    width: 100%;
  }
}
@media screen and (min-width: 1024px){
  .background-top {
    width: 80%;
  }
}
/* snow specific mq */
/* .sno-0 is always visible */
@media screen and (max-width: 767px) {
  .sno-1, .sno-2, .sno-3 {
    display: none;
  }
}
@media screen and (min-width: 768px) and (max-width: 1023px) {
  .sno-1 {
    display: block;
  }
  .sno-2, .sno-3 {
    display: none;
  }
}
@media screen and (min-width: 1024px) and (max-width: 1333px) {
  .sno-1, .sno-2 {
    display: block;
  }
  .sno-3 {
    display: none;
  }
}
@media screen and (min-width: 1333px) {
  .sno-1, .sno-2, .sno-3 {
    display: block;
  }
}
</style>
