// src/components/SourceButton/sourcebutton.tsx
import { component$, useSignal } from "@builder.io/qwik";
import { css } from "~/styled-system/css";
// import WinterIcon from "~/media/wintry-mini.png?jsx";

export interface SourcebuttonProps {
  img: string;
  url: string;
  text: string[];
}

export const Sourcebutton = component$<SourcebuttonProps>(
  ({ img, url, text }) => {
    const showCitation = useSignal(false);
    return (
      <div
        class={css({
          position: "fixed",
          top: "10px",
          right: "10px",
          zIndex: 100,
          display: "flex",
          flexDirection: "column",
          alignItems: "flex-end",
          justifyContent: "flex-start",
          gap: "8px",
          "& .qmark, .qanswer": {
            padding: "0 12px",
            margin: 0,
            transition: "opacity 250ms",
            color: "rgba(var(--bg-color-1))",
          },
          "& .qmark": {
            opacity: 0.7,
            height: "46px",
            width: "50px",
            fontSize: "24px",
            backgroundSize: "contain",
            backgroundRepeat: "no-repeat",
          },
          "& .qanswer": {
            background: "rgba(var(--fg-color-1), 1)",
            border: "1px solid rgba(var(--bg-color-1), 1)",
            // position: "relative",
            // top: "33px",
            fontSize: "0.77rem",
            opacity: 0.01,
            maxWidth: "200px",
          },
          "&:hover .qmark": {
            opacity: 0.99,
          },
          "&:hover .qanswer, .show": {
            opacity: 0.99,
          },
          "& em": {
            fontStyle: "italic",
          },
          "& a, em": {
            marginInline: "4px",
          },
        })}
      >
        <button
          onClick$={() => (showCitation.value = !showCitation.value)}
          class="qmark"
          style={`background-image: url('/collection-stories/${img}')`}
        >
          {" "}
          ?
        </button>
        <p class={`qanswer ${showCitation.value ? "show" : "noshow"}`}>
          {text[0]}
          <em>{text[1]}</em>
          <a href={url} target="_blank" class="rev-llines">
            View at the digital collections.{" "}
          </a>
          {text[2]}
        </p>
      </div>
    );
  },
);

// src/lib/components/SourceButton.svelte
<script lang="ts">
  type SourceButtonData = {
    data: {
      img: string;
      url: string;
      text: string[];
    }
  }
  export let data: SourceButtonData
  const { img, url, text } = data

  const bgimage =`url('/${img}');`
  let show = false

</script>

<div class="source-button">
  <button id="qmark" on:click={() => show = !show} style={`background-image: ${bgimage}`}>
    ?
  </button>
    <p class:show id="qanswer">
      {text[0]}
      <em>
        {text[1]}
      </em>
      <a href={ url } class="rev-llines">View at the digital collections.</a>
      {text[2]}
    </p>
</div>

<style lang="scss">
.source-button {
  position: sticky;
  top: 0;
  right: 0;
  padding: 20px 10px;
  display: flex;
  flex-direction: column;
  align-items: end;
  justify-content: start;
  gap: 8px;
}
#qmark, #qanswer {
  padding: 0 12px;
  margin: 0;
  transition: opacity 150ms;
  color: rgba(var(--bg-color-1), 1);
}
#qmark {
  opacity: 0.7;
  height: 46px;
  width: 50px;
  font-size: 24px;
  border: 0;
  background: none;
  background-size: contain;
  background-repeat: no-repeat;
}
#qanswer {
  background: rgba(var(--fg-color-1), 1);
  border: 1px solid rgba(var(--bg-color-1), 1);
  font-size: 0.77rem;
  opacity: 0.0001;
  max-width: 200px;
}
#qmark:hover ,#qmark:hover~#qanswer, #qanswer:hover, #qanswer.show {
  opacity: 0.99;
}
.rev-llines {
  color: inherit !important;
  font-weight: 700;
  line-height: 1rem;
  text-decoration: none;
  background: linear-gradient(
      to right,
      rgba(var(--bg-color-1), 0.3),
      rgba(var(--bg-color-1), 0.3)
    ),
    linear-gradient(
      to right,
      rgba(var(--bg-color-1), 1),
      rgba(var(--bg-color-1), 1)
    );
  background-size:
    100% 0.1rem,
    0 0.1rem;
  background-position:
    100% 100%,
    0 100%;
  background-repeat: no-repeat;
  transition: background-size 300ms;
}

.rev-llines:hover,
.rev-llines:focus {
  background-size:
    0 0.1rem,
    100% 0.1rem;
}
</style>
